apiVersion: v1
kind: Service
metadata:
  name: myminio-hl-nodeport   # 新Service名称
spec:
  type: NodePort        # 类型为NodePort
  selector:
    v1.min.io/tenant: myminio  # 使用原Service的Selector标签
  ports:
    - protocol: TCP
      port: 9000        # 服务端口（集群内部访问端口）
      targetPort: 9000   # Pod监听的端口（MinIO默认9000）
      nodePort: 30090    # 自定义NodePort端口（范围30000-32767）
