apiVersion: v2
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 9.14.3
description: Helm Chart for Apache SkyWalking BanyanDB
home: https://skywalking.apache.org
icon: https://raw.githubusercontent.com/apache/skywalking-kubernetes/master/logo/sw-logo-for-chart.jpg
name: skywalking-banyandb-helm
sources:
- https://github.com/apache/skywalking-banyandb-helm
version: 0.3.0
