apiVersion: v2
appVersion: 25.5.1
description: 'Doris Operator for creating, configuring and managing Doris clusters
  (dcr) and Doris disaggregated clusters (ddc). '
home: https://doris.apache.org
icon: https://charts.selectdb.com/images/doris.jpg
keywords:
- doris
- database
- olap
- sharding
kubeVersion: '>= 1.19'
maintainers:
- email: hudechao@selectdb.com
  name: Dechao Hu
name: doris-operator
sources:
- https://github.com/apache/doris-operator
type: application
version: 25.5.1
