apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    release: airflow
    tier: airflow
  name: airflow-ecmas-infra-files
  namespace: mw-ecmas
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    component: worker
  name: airflow-ecmas-worker
  namespace: mw-ecmas
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: worker
      release: airflow
      tier: airflow
  serviceName: airflow-worker
  template:
    metadata:
      # annotations:
      #   checksum/airflow-config: 7c7192e74222a4aa525ac88f9114ca5420b17c74cd0e1d1c77c4e1a8f9c17d33
      #   checksum/extra-configmaps: e862ea47e13e634cf17d476323784fa27dac20015550c230953b526182f5cac8
      #   checksum/extra-secrets: e9582fdd622296c976cbc10a5ba7d6702c28a24fe80795ea5b84ba443a56c827
      #   checksum/kerberos-keytab: 80979996aa3c1f48c95dfbe9bb27191e71f12442a08c0ed834413da9d430fd0e
      #   checksum/metadata-secret: 3b0b65ecefdd2055a5bbcab8cf1421511ac89c16083ce0791178114d6ffb5434
      #   checksum/pgbouncer-config-secret: 1dae2adc757473469686d37449d076b0c82404f61413b58ae68b3c5e99527688
      #   checksum/result-backend-secret: 98a68f230007cfa8f5d3792e1aff843a76b0686409e4a46ab2f092f6865a1b71
      #   checksum/webserver-secret-key: c1f2e91b85bc229c64f93dac4828a21387ff736cd677f43c707f65c83130277b
      #   cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
      # creationTimestamp: null
      labels:
        component: worker
        release: airflow
        tier: airflow
    spec:
      containers:
      - args:
        - bash
        - -c
        - |-
          exec \
          airflow celery worker -q remote
        env:
        - name: DUMB_INIT_SETSID
          value: "0"
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              key: fernet-key
              name: airflow-fernet-key
        - name: AIRFLOW_HOME
          value: /opt/airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW_CONN_AIRFLOW_DB
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: webserver-secret-key
              name: airflow-webserver-secret-key
        - name: AIRFLOW__CELERY__BROKER_URL
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-broker-url
        image: harbor.aliyun.com/middleware/apache/airflow-ecmas-worker:v0.1-20241210
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - CONNECTION_CHECK_MAX_COUNT=0 exec /entrypoint python -m celery --app
              airflow.providers.celery.executors.celery_executor.app inspect ping
              -d celery@$(hostname)
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 20
        name: worker
        ports:
        - containerPort: 8793
          name: worker-logs
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/logs
          name: logs
        - mountPath: /opt/airflow/airflow.cfg
          name: config
          readOnly: true
          subPath: airflow.cfg
        - mountPath: /opt/airflow/config/airflow_local_settings.py
          name: config
          readOnly: true
          subPath: airflow_local_settings.py
        - mountPath: /opt/airflow/dags
          name: dags
        - mountPath: /data/airflow/job-files/dev/DataCrafter-server
          name: ecmas-infra-files
        - mountPath: /data/airflow/job-files/prod/DataCrafter-server
          name: ecmas-infra-files
      - args:
        - bash
        - /clean-logs
        env:
        - name: AIRFLOW__LOG_RETENTION_DAYS
          value: "15"
        - name: AIRFLOW_HOME
          value: /opt/airflow
        image: harbor.aliyun.com/middleware/apache/airflow-ecmas-worker:v0.1-20241210
        imagePullPolicy: IfNotPresent
        name: worker-log-groomer
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/airflow/logs
          name: logs
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - airflow
        - db
        - check-migrations
        - --migration-wait-timeout=60
        env:
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              key: fernet-key
              name: airflow-fernet-key
        - name: AIRFLOW_HOME
          value: /opt/airflow
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW_CONN_AIRFLOW_DB
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-metadata
        - name: AIRFLOW__WEBSERVER__SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: webserver-secret-key
              name: airflow-webserver-secret-key
        - name: AIRFLOW__CELERY__BROKER_URL
          valueFrom:
            secretKeyRef:
              key: connection
              name: airflow-broker-url
        image: harbor.aliyun.com/middleware/apache/airflow-ecmas-worker:v0.1-20241210
        imagePullPolicy: IfNotPresent
        name: wait-for-airflow-migrations
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: 10m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /opt/airflow/airflow.cfg
          name: config
          readOnly: true
          subPath: airflow.cfg
        - mountPath: /opt/airflow/config/airflow_local_settings.py
          name: config
          readOnly: true
          subPath: airflow_local_settings.py
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsUser: 50000
      serviceAccount: airflow-worker
      serviceAccountName: airflow-worker
      terminationGracePeriodSeconds: 600
      volumes:
      - configMap:
          defaultMode: 420
          name: airflow-config
        name: config
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags
      - name: ecmas-infra-files
        persistentVolumeClaim:
          claimName: airflow-ecmas-infra-files
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: logs
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      volumeMode: Filesystem
