---
apiVersion: v1
kind: Service
metadata:
  name: xinference-nodeport
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    {{- .Values.serviceXinference.ports | toYaml | nindent 2 }}
  selector:
    app: xinference-supervisor