---
loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  ingester:
    chunk_encoding: snappy
    # # tracing 分布式链路追踪
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 4

  # 【修改点 1】更新规则存储路径，指向我们将要挂载的 /rules 目录
  rulerConfig:
    storage:
      type: local
      local:
        directory: /rules
    rule_path: /tmp/loki/rules-tmp
    alertmanager_url: http://kube-prom-stack-alertmanager.observe:9093
    ring:
      kvstore:
        store: inmemory
    enable_api: true
    enable_alertmanager_v2: true

#gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix

deploymentMode: Distributed

ingester:
  replicas: 3

#   # zoneAwareReplication.enabled: true（默认值通常是 true，取决于部署方式）
# 表示 Loki 在写入日志数据时，会尝试将 副本（replicas） 分布在 不同的故障域（如 AWS 的可用区、K8s 的 topology zones） 中，以提高容灾能力。
# zoneAwareReplication:
#    enabled: false
querier:
  replicas: 3
  maxUnavailable: 2
queryFrontend:
  replicas: 2
  maxUnavailable: 1
queryScheduler:
  replicas: 2
distributor:
  replicas: 3
  maxUnavailable: 2
compactor:
  replicas: 1
indexGateway:
  replicas: 2
  maxUnavailable: 1

# optional experimental components
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0

# Enable minio for storage
minio:
  enabled: true

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

singleBinary:
  replicas: 0

# 【修改点 2】新增 ruler 组件的挂载配置（与 loki, deploymentMode 同级）
ruler:
  extraVolumes:
    - name: loki-rules-configmap-volume
      configMap:
        name: loki-rules-configmap
  extraVolumeMounts:
    - name: loki-rules-configmap-volume
      mountPath: /rules
      readOnly: true
