apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-device-plugin-daemonset
  namespace: kube-system
  labels:
    app: nvidia-device-plugin
spec:
  selector:
    matchLabels:
      app: nvidia-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nvidia-device-plugin
    spec:
      # 使用 nodeAffinity 调度到有 gpu 标签的节点
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: Exists
      # 允许调度到有 GPU 污点的节点
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      # 系统关键优先级
      priorityClassName: "system-node-critical"
      containers:
      - name: nvidia-device-plugin-ctr
        image: harbor.aliyun.com/middleware/k8s-device-plugin:v0.16.1
        env:
          - name: FAIL_ON_INIT_ERROR
            value: "true"  # 初始化失败时重启 Pod
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: DirectoryOrCreate

